### ISSUE TITLE
API 3.2 pro autority - neúplná odpověď (?)

### ISSUE THREAD

**Issue by filak** [cbvk/obalkyknih#1]
Na webu uvádíte další údaje (biografické):
http://www.obalkyknih.cz/view_auth?auth_id=jk01083016

(Biogr./Hist. údaje: Narozena 4. 2. 1820 ve Vídni, zemřela 21. 1. 1862 v Praze. Prozaička, vlastním jménem Barbora, rozená Panklová.
Zdroj: Autoritní databáze Národní knihovny ČR)

Proč se tyto údaje nepropagují i přes API ?

**Comment by cbvk** [comment]
Dobry den,

protoze tyto udaje nikdo z knihoven nepozadoval ... maji vlastni zaznamy  nechteji je prehravat zaznamy z NKP.cz
Vy je potrebujete?

asi je muzeme pridat - otazkou je jestli NKP.cz toto povoli 

J.Nechvatal

**Comment by filak** [comment]
No tak jednou je to verejna autorita, tak by to snad nemelo vadit. At se propaguje kompletni. Vyuziti pro to urcite mame.

**Comment by cbvk** [comment]
OK, pokusime se 
J.N.

**Comment by cbvk** [comment]
pridano - jako parametr auth_biographical_or_historical_data
priklad
http://cache.obalkyknih.cz/api/auth/meta?auth_id=jk01083016

J.N.

**Comment by filak** [comment]
Opozdene diky! Zdravim
