### ISSUE TITLE
Obalky API - "duplikace" bibinfo objektu

### ISSUE THREAD

**Issue by filak** [cbvk/obalkyknih#10]
Příklad:

http://cache.obalkyknih.cz/api/books?multi=[{"nbn":"ABA008-MED00010976","isbn":"0008-7335"},{"nbn":"ABE291-MED00010976","isbn":"0008-7335"}]

API správně vrátí 2 objekty, ale obsah bibinfo.nbn je v obou objektech totožný:

`"bibinfo": {
"nbn": "ABE291-MED00010976",
"isbn": "0008-7335"
}`

Nelze tedy první objekt spárovat s ID příslušného HTML elementu přes řetězec nbn.

Očekával bych, že v prvním objektu bude bibinfo.nbn z prvního objektu z multi požadavku:

"nbn": "**ABA008**-MED00010976"

Alespoň podle dokumentace verze 3.3 by to tak mělo být:

> Odpověď obsahuje pole bibinfo, které je kopií parametrů použitých v dotazu. Slouží pro zpětné párování odpovědi na dotaz na straně KIS (např. v případě, že se dotazujeme na více děl najednou). Doporučené je spoléhat se na pořadí. Položka č.1 v meta datovém poli objektů odpovídá položce č.1 v dotazu.

**Comment by filak** [comment]
Chystá se to někdo řešit ?

**Comment by cosmo-cz** [comment]
Zprávu jsem zaregistroval až teď. Problém je v řešení.

**Comment by cosmo-cz** [comment]
Problém opravený. Děkuji za nahlášení a omlouvám se za zdržení.

**Comment by filak** [comment]
Díky.
