### ISSUE TITLE
API jmenných autorit - podpora parametru multi ?

### ISSUE THREAD

**Issue by filak** [cbvk/obalkyknih#14]
Nešlo by udělat volání API autorit také jako multi ?

Třeba takto:
/api/auth?multi=[{"auth_id":"jk01101766"},{"auth_id":"jk01101764"}]

**Comment by cosmo-cz** [comment]
Zdravím. Je možné volání:
/api/auth/meta?auth_id=jk01101766,jk01101764
Odpověď je pole se steným pořadím identifikátorů.

**Comment by filak** [comment]
OK. Toho jsem si v dokumentaci nevšimnul. Díky!
