### ISSUE TITLE
Jak zjistit přes API, že dokument má více než jednu obálku resp. obsah

### ISSUE THREAD

**Issue by zabak** [cbvk/obalkyknih#2]
Potřebovali bychom uživateli nějak naznačit, že má smysl kliknout na obálku, protože se mu zobrazí další obálky (ať už u periodik, nebo vícesvazkových děl). K tomu bychom potřebovali informaci že obálky knih nabízejí více než jednu obálku. A totéž by bylo fajn i pro obsahy.

**Comment by cbvk** [comment]
v metadatovem kontajneru:
napr.
cache.obalkyknih.cz/api/books?multi=[{"nbn":"cnb002657961"}]&sigla=CBA001&pretty=1

parametr "succ_cover_count" obashuje pocet dostupnych obalek 

parametr "succ_toc_count" obsahuje pocet obashu 

JN
