### ISSUE TITLE
Statistiky - grafy se zdají být neaktualizované

### ISSUE THREAD

**Issue by filak** [cbvk/obalkyknih#23]
V Nastavení sekci Statistiky (https://www.obalkyknih.cz/account_stats) jsou 2 grafy - denní a měsíční přehled dotazů na API...

Pro siglu ABA008 - denní přehled končí datem 1.1. a mesíční končí datem 16.7. - což se mi zdá obojí divné.
![Obalky_2021-10-06_10-15-04](https://user-images.githubusercontent.com/1353748/136165716-5eda13ac-3c94-4476-b682-7e824810ff10.png)

**Comment by filak** [comment]
Čte to tady někdo ?

**Comment by cosmo-cz** [comment]
Zdravím. Čteme. A věci se věnujeme. Zatím pozdravujeme a přejeme hezký den.

**Comment by cosmo-cz** [comment]
Data jsem promazal a teď se zobrazují od 5.11. a novější. Celkové počty jsou vypadá vpořádky (ty vidí administrátor), ale tyto s rozpadem na siglu ne (vidí knihovny), proto to pročištění. Na denním grafu je vidět 2 ty samé dny vedle sebe, to se ztratí až se graf zaplní. Měsíční graf obsahuje pouze data od listopadu 2021 (od 5.11.), proto osa X obsahuje pouze jednu položku (zatím, bude se plnit).

**Comment by filak** [comment]
OK, dekuji a zaviram.
