### ISSUE TITLE
Nezobrazují se autoři - obálky se přitom zobrazují 

### ISSUE THREAD

**Issue by filak** [cbvk/obalkyknih#28]
Například:
Purkyně, Jan Evangelista

https://www.obalkyknih.cz/view_auth?auth_id=jk01101764

https://cache.obalkyknih.cz/api/auth/meta?auth_id=jk01101764

https://www.medvik.cz/link/jk01101764

Odpověď serveru je:

```
Unknown referer. You need to sign up at http://www.obalkyknih.cz and provide your catalog URL; Referer: https://www.medvik.cz/  IP: 10.130.0.254, 195.113.87.240
```

Přitom obálky se zobrazují normálně - https://www.medvik.cz/link/MED00169760 - takže nastavení pro ABA008 se mi zdá v pořádku.

**Comment by cosmo-cz** [comment]
Opravené. Prosím o kontrolu.

**Comment by filak** [comment]
Funguje! Diky a zdravim.
