### ISSUE TITLE
Padání klienta

### ISSUE THREAD

**Issue by OgDInstant** [cbvk/obalkyknih#4]
Verze 0.37 při načtení dokumentu přez čárový kód 9781446294369 (ISBN 978-1-4462-9436-9) spadne s hláškou: Program ObálkyKnih_scanner přestal správně pracovat. Otestováno ve verzi 0.34 tato chaba nenastává.

Nastavení Z39.50 serveru:
Sigla knihovny: ABA013
Báze záznamu: STK01
Z39.50 Server URL: aleph.techlib.cz
Z39.50 Server Port: 9991
Z39.50 Databáze: STK01
Kódování: UTF-8 (Unicode)
Čárový kód: 1063
ČNB: 48

děkuji za řešení
Jan Kolátor (Národní technická knihovna)

**Comment by OgDInstant** [comment]
Update problém nastane vždy kdy je v záznamu v poli 020 prohozeno podpole "z" a "a". V okamžiku kdy se pole z vyskytuje před polem a dojde k pádu aplikace.

Referenční záznam který sem uvedl již jsme si opravili.

**Comment by cosmo-cz** [comment]
Dobrý den. Tady je odkaz na opravenou aplikaci:
https://mega.nz/#!KOxzXY7L!MxqUyJmZXW5kiF0broaOhnbvJNEnoZmtTTBVg8ZX1pU
Bude taky zahrnuto do verze 0.38.
