### ISSUE TITLE
API response vrací v URL 127.0.0.1

### ISSUE THREAD

**Issue by filak** [cbvk/obalkyknih#5]
Například:
...
backlink_url: "https://www.obalkyknih.cz/view?nbn=aba008-med00183872"
bib_author: "Roman Jirák,  Vanda Franková,  Jakub Hort"
bib_title: "Alzheimerova choroba : informace pro pacienty : cesta z labyrintu zapomínání"
bibinfo: {nbn: "ABA008-MED00183872"}
book_id: "127002155"
cover_icon_url: "https://**127.0.0.1**/file/cover/2004143/icon"
cover_medium_url: "https://**127.0.0.1**/file/cover/2004143/medium"
cover_preview510_url: "https://**127.0.0.1**/file/cover/2004143/preview510"
cover_thumbnail_url: "https://**127.0.0.1**/file/cover/2004143/thumbnail"
...
toc_pdf_url: "https://**127.0.0.1**/file/toc/425286/pdf"
toc_thumbnail_url: "https://**127.0.0.1**/file/toc/425286/thumbnail"

Nemělo by tam být cache.obalkyknih.cz, resp. cache2.obalkyknih.cz ?

**Comment by cosmo-cz** [comment]
Dobrý den.
Opraveno.

**Comment by filak** [comment]
Opožděně děkuji a zavírám.
