### ISSUE TITLE
Více ISBN knihy nevrací "obálku", i když existuje

### ISSUE THREAD

**Issue by matyasbajger** [cbvk/obalkyknih#7]
Pokud zavolám API na všechny 3 ISBN titulu
[{"isbn":"978-80-7482-298-8","isbn":"978-80-7482-299-5","isbn":"978-80-7482-300-8"}]
http://cache.obalkyknih.cz/api/books?multi=%5B%7B%22isbn%22%3A%22978-80-7482-298-8%22%2C%22isbn%22%3A%22978-80-7482-299-5%22%2C%22isbn%22%3A%22978-80-7482-300-8%22%7D%5D

nevraci nic
[{"flag_bare_record":1,"ean":"978-80-7482-300-8","bibinfo":{"isbn":"978-80-7482-300-8"},"_id":"5c94b66b93386270f9888d34"}]

Ale pokud vyberu JEN PRVNI ISBN
[{"isbn":"978-80-7482-298-8"}]
http://cache.obalkyknih.cz/api/books?multi=%5B%7B%22isbn%22%3A%22978-80-7482-298-8%22%7D%5D                                           

dostavam uplnou odpoved:
[{"_id":"5c8be096e9b2a56fc6c275bc","succ_toc_count":"0","cover_preview510_url":"https://cache.obalkyknih.cz/file/cover/2089640/preview510","ean":"9788074822988","orig_width":"300","succ_cover_count":"0","flag_bare_record":0,"bibinfo":{"isbn":"978-80-7482-298-8"},... .... .....

Prosím o prověření.

**Comment by cbvk** [comment]
Parameter multi je pole objektov.
Zavorky [ ] znamenaju pole a v nom moze byt viac objektov { }

Tunaka je objekt
{"isbn":"978-80-7482-299-5","isbn":"978-80-7482-300-8","isbn":"978-80-7482-298-8"}
a "isbn" vo vnutri su vlastnosti/property. 3x su nastavene za sebou
propety s tym istym nazvom, takze plati posledna hodnota. To je podobne,
ako keby bolo pod sebou napisane:

obj.isbn = "978-80-7482-299-5";
obj.isbn = "978-80-7482-300-8";
obj.isbn = "978-80-7482-298-8";

takze plati posledna hodnota.

Alebo jednoduchsi priklad:
x = 1
x = 2
x = 3
Takze vysledok je 3.

Moze to spravit dotazom, ktory mu vrati 3 vysledky:
[{"isbn":"978-80-7482-299-5"}, {"isbn":"978-80-7482-300-8"},
{"isbn":"978-80-7482-298-8"}]

Ale to nechce.

To co by chcel je pole objektov, ktoreho vlastnost moze byt opet pole:
[{"isbn":["978-80-7482-299-5", "978-80-7482-300-8", "978-80-7482-298-8"]}]

Ale to API v sucasnosti nepodporuje.

Zdatim neuazujeme o implementaci ...


JN
