### ISSUE TITLE
http 404 pri pridani noveho hodnoceni

### ISSUE THREAD

**Issue by matyasbajger** [cbvk/obalkyknih#8]
Hezky den!
Pokud chceme pridat nove hodnoceni pres API, konrketne POST pozadavek
http(s)://cache2.obalkyknih.cz/?add_review=true&book_id=110036895&id=1555054669360
+ POST data: rating_value: 4
Vraci se odpoved http 404 (not found)
Pozadavek jde ze serveru aleph.osu.cz / 78.128.128.5

Je prosim problem nekde na nasi strane a funguje pridavani hodnoceni u dalsich knihoven?
Dekuji!
Matyas Bajger, Ostrava

**Comment by cbvk** [comment]
dle me chodi OK:
priklady ...

https://obalkyknih.cz/view?book_id=110071296
https://obalkyknih.cz/view?book_id=111467678
https://obalkyknih.cz/view?book_id=122883377

posledni je treba z JVK z katalogu 
mam kontaktovat progrmatora ...

diky 

JN

**Comment by cosmo-cz** [comment]
Dnes jsem zkousel a vypada vporadku. Prikladam html stranku, kterou jsem testoval (IP z ktere se pozadavek odesle musi byt registrovana, co 78.128.128.5 je).
To matyasbajger: nemate info, jestli je v Aleph uz vporadku, nebo se to opakovalo?

[query_rating.html.zip](https://github.com/cbvk/obalkyknih/files/3182343/query_rating.html.zip)

**Comment by matyasbajger** [comment]
Problem byl v knihovne OU (osu.cz) a pricina nikoli na cilovem serveru obalkyknih.cz, ale v presmerovani v Apachi na Aleph serveru. Hodnoceni je totiz v OPAC pridavano JS a kvuli IP omezenim nejsou volany rovnou obalkyknih.cz, ale Aleph server, kde je pomoci Apache presmerovano na obalkyknih.cz. Po dohode s OU bylo posilani hodnoceni na server obalkyknih.cz zruseno. Bohuzel tak neni nyni posilani funkcni, ale problem je cely na vlastni strane (v tom presmerovani).
