### ISSUE TITLE
SkenKlient : Chyba při stahování metadat - daný klíč není ve slovníku...

### ISSUE THREAD

**Issue by filak** [cbvk/obalkyknih#9]
Při pokusu o stažení následujících záznamů přes URN-NBN se objevuje hláška

![Obalky-error-2019-04-12](https://user-images.githubusercontent.com/1353748/56048696-536a1380-5d48-11e9-9a67-07ce60cc9c3b.png)

MED00185294
MED00185297

Marc:
http://oai.medvik.cz/medvik/oai?verb=GetRecord&identifier=oai:medvik.cz:196699&metadataPrefix=xml-marc

http://oai.medvik.cz/medvik/oai?verb=GetRecord&identifier=oai:medvik.cz:196702&metadataPrefix=xml-marc

Klient verze 0.38

**Comment by filak** [comment]
Tak jak to vypada?

**Comment by cosmo-cz** [comment]
Prosim o zaslani nastaveni vaseho skenovaciho klienta, pripojeni na zserver.
Postaci screenshot teto zalozky:

**Comment by filak** [comment]
![obalky-nastaveni](https://user-images.githubusercontent.com/1353748/57689902-c533c680-7640-11e9-8764-a5f8d5bba73b.png)

**Comment by cosmo-cz** [comment]
Data zaslane Z-serverem ma problem skenovaci klient rozkodovat. Ma to problem rozkodovat i yaz client viz. screenshot co je hodne zvlastni, takze se domnivam, ze je problem na strane zdroje dat, ne v skenovacim klientu.

Co jsem zkousel ruzne zservery, tak RAW MARC zaznam vypada tak, ze jsou vyjmenovane cisla tagu, nasledovane delkou tagu v bajtech, nasledovane pozici na kterem bajtu tag zacina. Ale data ze zaznamu MED00185294 jsou jina. Nemaji pocatecni pozici.
Zaznam MED00185294 ji ma a zaznam je yaz klientem rozkodovan spravne.

![yaz-problem-rawdata](https://user-images.githubusercontent.com/5089334/57741690-539a5d80-76be-11e9-86fb-a73f9fde5d25.png)

Vystup yaz klienta:

![yaz-problem](https://user-images.githubusercontent.com/5089334/57741682-48473200-76be-11e9-8cb3-d51eab7c6c2f.png)

Tady jsou MARC zaznamy v RAW formatu: Prvni je spatny, druhy spravny:

[medvik.006.txt](https://github.com/cbvk/obalkyknih/files/3180484/medvik.006.txt)
[medvik.022.txt](https://github.com/cbvk/obalkyknih/files/3180485/medvik.022.txt)

**Comment by filak** [comment]
Zajímavé, díky za analýzu. Podívám se na to.

**Comment by cosmo-cz** [comment]
Mate takovych zaznamu hodne?
Pokud ano a nepovede se vam to vyresit byla by moznost rozlisovat od 25 bajtu tento vyraz 001\d{4}00000 a podle toho se rozhodovat, ze data jsou v jinem formatu a ma sledovat delimitery. Ale na druhou stranu i jine systemy budou mit se zaznamy problem, dost se spoleha na knihovnu lib-yaz, nebo perlovy zoom a minimalne yaz s tim ma problem.

**Comment by filak** [comment]
Jedna se o stazene zaznamy, maji vadny leader. To si musime nejak osetrit, aby k tomu nedochazelo.
